name: Gatsby Publish

on:
  push:
    branches:
      - gatsby-refactor

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_PAGES_DEPLOY }}
          deploy-branch: gh-pages
          deploy-repo: elocaters-notes.github.io

